# Generated by Django 4.2.4 on 2023-09-22 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='profile_pic',
            field=models.ImageField(blank=True, default='static/images/profile_pic.jpeg', null=True, upload_to=''),
        ),
    ]
