# Generated by Django 4.2.4 on 2023-09-22 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
